// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth_sessions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO auth_sessions (
  id, user_id, token_hash, idle_expires_at, absolute_expires_at, created_at, last_seen_at
) VALUES ($1, $2, $3, $4, $5, $6, $6)
RETURNING id, user_id, token_hash, csrf_token_hash, idle_expires_at, absolute_expires_at, created_at, last_seen_at
`

type CreateAuthSessionParams struct {
	ID                uuid.UUID `json:"id"`
	UserID            uuid.UUID `json:"user_id"`
	TokenHash         []byte    `json:"token_hash"`
	IdleExpiresAt     time.Time `json:"idle_expires_at"`
	AbsoluteExpiresAt time.Time `json:"absolute_expires_at"`
	CreatedAt         time.Time `json:"created_at"`
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
		arg.CreatedAt,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CsrfTokenHash,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const deleteAuthSessionByTokenHash = `-- name: DeleteAuthSessionByTokenHash :exec
DELETE FROM auth_sessions WHERE token_hash = $1
`

func (q *Queries) DeleteAuthSessionByTokenHash(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteAuthSessionByTokenHash, tokenHash)
	return err
}

const deleteExpiredAuthSession = `-- name: DeleteExpiredAuthSession :exec
DELETE FROM auth_sessions WHERE id = $1 AND (idle_expires_at <= $2 OR absolute_expires_at <= $2)
`

type DeleteExpiredAuthSessionParams struct {
	ID            uuid.UUID `json:"id"`
	IdleExpiresAt time.Time `json:"idle_expires_at"`
}

func (q *Queries) DeleteExpiredAuthSession(ctx context.Context, arg DeleteExpiredAuthSessionParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredAuthSession, arg.ID, arg.IdleExpiresAt)
	return err
}

const getAuthSessionByTokenHash = `-- name: GetAuthSessionByTokenHash :one
SELECT id, user_id, token_hash, csrf_token_hash, idle_expires_at, absolute_expires_at, created_at, last_seen_at FROM auth_sessions WHERE token_hash = $1
`

func (q *Queries) GetAuthSessionByTokenHash(ctx context.Context, tokenHash []byte) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getAuthSessionByTokenHash, tokenHash)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CsrfTokenHash,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const setAuthSessionCSRFHash = `-- name: SetAuthSessionCSRFHash :exec
UPDATE auth_sessions SET csrf_token_hash = $2 WHERE id = $1
`

type SetAuthSessionCSRFHashParams struct {
	ID            uuid.UUID `json:"id"`
	CsrfTokenHash []byte    `json:"csrf_token_hash"`
}

func (q *Queries) SetAuthSessionCSRFHash(ctx context.Context, arg SetAuthSessionCSRFHashParams) error {
	_, err := q.db.Exec(ctx, setAuthSessionCSRFHash, arg.ID, arg.CsrfTokenHash)
	return err
}

const touchAuthSession = `-- name: TouchAuthSession :exec
UPDATE auth_sessions SET last_seen_at = $2, idle_expires_at = $3 WHERE id = $1
`

type TouchAuthSessionParams struct {
	ID            uuid.UUID `json:"id"`
	LastSeenAt    time.Time `json:"last_seen_at"`
	IdleExpiresAt time.Time `json:"idle_expires_at"`
}

func (q *Queries) TouchAuthSession(ctx context.Context, arg TouchAuthSessionParams) error {
	_, err := q.db.Exec(ctx, touchAuthSession, arg.ID, arg.LastSeenAt, arg.IdleExpiresAt)
	return err
}
