// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tasks.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
  id, workspace_id, title, description, status, assignee_user_id,
  created_by_user_id, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $8)
RETURNING id, workspace_id, title, description, status, assignee_user_id, created_by_user_id, created_at, updated_at
`

type CreateTaskParams struct {
	ID              uuid.UUID  `json:"id"`
	WorkspaceID     uuid.UUID  `json:"workspace_id"`
	Title           string     `json:"title"`
	Description     string     `json:"description"`
	Status          string     `json:"status"`
	AssigneeUserID  *uuid.UUID `json:"assignee_user_id"`
	CreatedByUserID uuid.UUID  `json:"created_by_user_id"`
	CreatedAt       time.Time  `json:"created_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.WorkspaceID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.AssigneeUserID,
		arg.CreatedByUserID,
		arg.CreatedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeUserID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE workspace_id = $1 AND id = $2
`

type DeleteTaskParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.Exec(ctx, deleteTask, arg.WorkspaceID, arg.ID)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, workspace_id, title, description, status, assignee_user_id, created_by_user_id, created_at, updated_at FROM tasks WHERE workspace_id = $1 AND id = $2
`

type GetTaskParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, arg.WorkspaceID, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeUserID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, workspace_id, title, description, status, assignee_user_id, created_by_user_id, created_at, updated_at FROM tasks
WHERE workspace_id = $1 AND ($2::text IS NULL OR status = $2)
ORDER BY updated_at DESC, id DESC
`

type ListTasksParams struct {
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	Status      pgtype.Text `json:"status"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks, arg.WorkspaceID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.AssigneeUserID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks SET title = $3, description = $4, status = $5,
  assignee_user_id = $6, updated_at = $7
WHERE workspace_id = $1 AND id = $2
RETURNING id, workspace_id, title, description, status, assignee_user_id, created_by_user_id, created_at, updated_at
`

type UpdateTaskParams struct {
	WorkspaceID    uuid.UUID  `json:"workspace_id"`
	ID             uuid.UUID  `json:"id"`
	Title          string     `json:"title"`
	Description    string     `json:"description"`
	Status         string     `json:"status"`
	AssigneeUserID *uuid.UUID `json:"assignee_user_id"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.WorkspaceID,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.AssigneeUserID,
		arg.UpdatedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeUserID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
