#!/usr/bin/env node
// Generates the Material Design 3 reference tonal palettes for tokens.css.
//
// The generated hex values are committed into packages/ui/src/styles/tokens.css,
// which is the only file allowed to contain concrete colors. This script is a
// build-time tool: @material/material-color-utilities is a devDependency and
// never ships to the browser.
//
// Usage: pnpm --filter @project-template/ui generate:tokens

import { argbFromHex, Hct, hexFromArgb, SchemeTonalSpot, TonalPalette } from "@material/material-color-utilities";

const SEED = "#77b55a"; // SITCON brand green
const WARNING_SEED = "#946200"; // MD3 has no warning role; SITCON needs one.

// Neutral carries the surface-container ladder, which needs tones MD3's other
// palettes never reference (4/6/12/17/22/24 dark, 87/92/94/96 light).
const NEUTRAL_TONES = [0, 4, 6, 10, 12, 17, 20, 22, 24, 25, 30, 35, 40, 50, 60, 70, 80, 87, 90, 92, 94, 95, 96, 98, 99, 100];
const ACCENT_TONES = [0, 10, 20, 25, 30, 35, 40, 50, 60, 70, 80, 90, 95, 99, 100];

function emit(name, palette, tones) {
	const lines = [`\t/* ${name} */`];
	for (const tone of tones) lines.push(`\t--md-ref-palette-${name}${tone}: ${hexFromArgb(palette.tone(tone))};`);
	return lines.join("\n");
}

const scheme = new SchemeTonalSpot(Hct.fromInt(argbFromHex(SEED)), false, 0);
const warningHct = Hct.fromInt(argbFromHex(WARNING_SEED));
const warning = TonalPalette.fromHueAndChroma(warningHct.hue, 60);

const blocks = [
	emit("primary", scheme.primaryPalette, ACCENT_TONES),
	emit("secondary", scheme.secondaryPalette, ACCENT_TONES),
	emit("tertiary", scheme.tertiaryPalette, ACCENT_TONES),
	emit("error", scheme.errorPalette, ACCENT_TONES),
	emit("warning", warning, ACCENT_TONES),
	emit("neutral", scheme.neutralPalette, NEUTRAL_TONES),
	emit("neutral-variant", scheme.neutralVariantPalette, NEUTRAL_TONES)
];

process.stdout.write(`\t/* Generated by scripts/generate-tokens.mjs from seed ${SEED}. Do not hand-edit. */\n`);
process.stdout.write(blocks.join("\n\n") + "\n");
