/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get API status */
		get: operations["getAPIStatus"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/csrf": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get CSRF token */
		get: operations["getCSRFToken"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Log in user */
		post: operations["loginUser"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/logout": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Log out user */
		post: operations["logoutUser"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/me": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get current user */
		get: operations["getCurrentUser"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/register": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Register user */
		post: operations["registerUser"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/healthz": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get health status */
		get: operations["getHealth"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/workspaces": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List workspaces */
		get: operations["listWorkspaces"];
		put?: never;
		/** Create workspace */
		post: operations["createWorkspace"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/workspaces/{workspaceId}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get workspace */
		get: operations["getWorkspace"];
		put?: never;
		post?: never;
		/** Delete workspace */
		delete: operations["deleteWorkspace"];
		options?: never;
		head?: never;
		/** Update workspace */
		patch: operations["updateWorkspace"];
		trace?: never;
	};
	"/workspaces/{workspaceId}/members": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List workspace members */
		get: operations["listWorkspaceMembers"];
		put?: never;
		/** Add workspace member */
		post: operations["addWorkspaceMember"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/workspaces/{workspaceId}/members/{userId}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Remove workspace member */
		delete: operations["removeWorkspaceMember"];
		options?: never;
		head?: never;
		/** Update workspace member */
		patch: operations["updateWorkspaceMember"];
		trace?: never;
	};
	"/workspaces/{workspaceId}/tasks": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List tasks */
		get: operations["listTasks"];
		put?: never;
		/** Create task */
		post: operations["createTask"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/workspaces/{workspaceId}/tasks/{taskId}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get task */
		get: operations["getTask"];
		put?: never;
		post?: never;
		/** Delete task */
		delete: operations["deleteTask"];
		options?: never;
		head?: never;
		/** Update task */
		patch: operations["updateTask"];
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/**
		 * @example {
		 *       "name": "Project Template API",
		 *       "version": "0.1.0"
		 *     }
		 */
		APIStatusResponse: {
			/** @enum {string} */
			name: "Project Template API";
			version: string;
		};
		/**
		 * @example {
		 *       "email": "editor@example.com",
		 *       "role": "editor"
		 *     }
		 */
		AddWorkspaceMemberRequest: {
			email: components["schemas"]["email"];
			/** @enum {string} */
			role: "owner" | "editor" | "viewer";
		};
		/**
		 * @example {
		 *       "user": {
		 *         "id": "11111111-1111-1111-1111-111111111111",
		 *         "email": "owner@example.com",
		 *         "displayName": "Alex Morgan",
		 *         "createdAt": "2026-07-10T08:00:00Z",
		 *         "updatedAt": "2026-07-10T08:00:00Z"
		 *       }
		 *     }
		 */
		AuthResponse: {
			user: components["schemas"]["User"];
		};
		/**
		 * @example {
		 *       "token": "a-one-time-readable-csrf-token"
		 *     }
		 */
		CSRFResponse: {
			/** Format: password */
			token: string;
		};
		/**
		 * @example {
		 *       "title": "Publish architecture decision record",
		 *       "description": "Document transaction ownership for workspace creation.",
		 *       "assigneeId": "11111111-1111-1111-1111-111111111111"
		 *     }
		 */
		CreateTaskRequest: {
			title: string;
			description?: string;
			/** @enum {string} */
			status?: "todo" | "in_progress" | "done";
			assigneeId?: components["schemas"]["uuid"] | null;
		};
		/**
		 * @example {
		 *       "name": "Product Engineering"
		 *     }
		 */
		CreateWorkspaceRequest: {
			name: string;
		};
		/**
		 * @example {
		 *       "status": "ok"
		 *     }
		 */
		HealthResponse: {
			/** @enum {string} */
			status: "ok";
		};
		/**
		 * @example {
		 *       "email": "owner@example.com",
		 *       "password": "correct-horse-battery-staple"
		 *     }
		 */
		LoginRequest: {
			email: components["schemas"]["email"];
			/** Format: password */
			password: string;
		};
		/**
		 * @example {
		 *       "type": "https://project-template.example/problems/validation-failed",
		 *       "title": "Validation failed",
		 *       "status": 422,
		 *       "code": "VALIDATION_FAILED",
		 *       "detail": "One or more request fields are invalid.",
		 *       "requestId": "req_01J00000000000000000000000",
		 *       "errors": [
		 *         {
		 *           "code": "REQUIRED",
		 *           "message": "title is required",
		 *           "location": "body.title"
		 *         }
		 *       ]
		 *     }
		 */
		ProblemDetails: {
			/** Format: uri */
			type: string;
			title: string;
			/** Format: int32 */
			status: number;
			/** @enum {string} */
			code:
				| "BAD_REQUEST"
				| "UNAUTHORIZED"
				| "FORBIDDEN"
				| "NOT_FOUND"
				| "CONFLICT"
				| "VALIDATION_FAILED"
				| "INTERNAL_ERROR"
				| "SERVICE_UNAVAILABLE"
				| "METHOD_NOT_ALLOWED"
				| "AUTH_MISSING_SESSION"
				| "AUTH_INVALID_SESSION"
				| "AUTH_INVALID_CREDENTIALS"
				| "AUTH_INVALID_CSRF"
				| "INSUFFICIENT_ROLE"
				| "EMAIL_ALREADY_EXISTS"
				| "WORKSPACE_NOT_FOUND"
				| "WORKSPACE_MEMBER_NOT_FOUND"
				| "WORKSPACE_MEMBER_ALREADY_EXISTS"
				| "WORKSPACE_LAST_OWNER"
				| "TASK_ASSIGNEE_NOT_MEMBER"
				| "TASK_NOT_FOUND";
			detail?: string;
			requestId?: string;
			errors?: components["schemas"]["ProblemError"][];
		};
		/**
		 * @example {
		 *       "code": "REQUIRED",
		 *       "message": "title is required",
		 *       "location": "body.title"
		 *     }
		 */
		ProblemError: {
			/** @enum {string} */
			code:
				| "INVALID_VALUE"
				| "INVALID_JSON"
				| "INVALID_LENGTH"
				| "INVALID_FORMAT"
				| "INVALID_ENUM"
				| "NOT_A_WORKSPACE_MEMBER"
				| "REQUIRED"
				| "VALUE_TOO_SHORT"
				| "VALUE_TOO_LONG";
			message: string;
			location?: string;
		};
		/**
		 * @example {
		 *       "email": "owner@example.com",
		 *       "displayName": "Alex Morgan",
		 *       "password": "correct-horse-battery-staple"
		 *     }
		 */
		RegisterRequest: {
			email: components["schemas"]["email"];
			displayName: string;
			/** Format: password */
			password: string;
		};
		/**
		 * @example {
		 *       "id": "33333333-3333-3333-3333-333333333333",
		 *       "workspaceId": "22222222-2222-2222-2222-222222222222",
		 *       "title": "Publish architecture decision record",
		 *       "description": "Document transaction ownership for workspace creation.",
		 *       "status": "in_progress",
		 *       "assigneeId": "11111111-1111-1111-1111-111111111111",
		 *       "createdAt": "2026-07-10T09:00:00Z",
		 *       "updatedAt": "2026-07-10T09:30:00Z"
		 *     }
		 */
		Task: {
			id: components["schemas"]["uuid"];
			workspaceId: components["schemas"]["uuid"];
			title: string;
			description: string;
			/** @enum {string} */
			status: "todo" | "in_progress" | "done";
			assigneeId: components["schemas"]["uuid"] | null;
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
		};
		TaskListResponse: {
			tasks: components["schemas"]["Task"][];
		};
		TaskResponse: {
			task: components["schemas"]["Task"];
		};
		/**
		 * @example {
		 *       "title": "Publish the architecture decision record",
		 *       "status": "done",
		 *       "assigneeId": "11111111-1111-1111-1111-111111111111"
		 *     }
		 */
		UpdateTaskRequest: {
			title?: string;
			description?: string;
			/** @enum {string} */
			status?: "todo" | "in_progress" | "done";
			assigneeId?: components["schemas"]["uuid"] | null;
		};
		/**
		 * @example {
		 *       "role": "viewer"
		 *     }
		 */
		UpdateWorkspaceMemberRequest: {
			/** @enum {string} */
			role: "owner" | "editor" | "viewer";
		};
		/**
		 * @example {
		 *       "name": "Platform Engineering"
		 *     }
		 */
		UpdateWorkspaceRequest: {
			name: string;
		};
		/**
		 * @example {
		 *       "id": "11111111-1111-1111-1111-111111111111",
		 *       "email": "owner@example.com",
		 *       "displayName": "Alex Morgan",
		 *       "createdAt": "2026-07-10T08:00:00Z",
		 *       "updatedAt": "2026-07-10T08:00:00Z"
		 *     }
		 */
		User: {
			id: components["schemas"]["uuid"];
			email: components["schemas"]["email"];
			displayName: string;
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
		};
		/**
		 * @example {
		 *       "id": "22222222-2222-2222-2222-222222222222",
		 *       "name": "Product Engineering",
		 *       "role": "owner",
		 *       "createdByUserId": "11111111-1111-1111-1111-111111111111",
		 *       "createdAt": "2026-07-10T08:10:00Z",
		 *       "updatedAt": "2026-07-10T08:10:00Z"
		 *     }
		 */
		Workspace: {
			id: components["schemas"]["uuid"];
			name: string;
			/** @enum {string} */
			role: "owner" | "editor" | "viewer";
			createdByUserId: components["schemas"]["uuid"];
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
		};
		WorkspaceListResponse: {
			workspaces: components["schemas"]["Workspace"][];
		};
		/**
		 * @example {
		 *       "userId": "11111111-1111-1111-1111-111111111111",
		 *       "email": "owner@example.com",
		 *       "displayName": "Alex Morgan",
		 *       "role": "owner",
		 *       "createdAt": "2026-07-10T08:10:00Z"
		 *     }
		 */
		WorkspaceMember: {
			userId: components["schemas"]["uuid"];
			email: components["schemas"]["email"];
			displayName: string;
			/** @enum {string} */
			role: "owner" | "editor" | "viewer";
			/** Format: date-time */
			createdAt: string;
		};
		WorkspaceMemberListResponse: {
			members: components["schemas"]["WorkspaceMember"][];
		};
		WorkspaceMemberResponse: {
			member: components["schemas"]["WorkspaceMember"];
		};
		WorkspaceResponse: {
			workspace: components["schemas"]["Workspace"];
		};
		/** Format: email */
		email: string;
		/** Format: uuid */
		uuid: string;
	};
	responses: never;
	parameters: {
		CSRFHeader: string;
		TaskIdPath: components["schemas"]["uuid"];
		TaskListQuery: "todo" | "in_progress" | "done";
		UserIdPath: components["schemas"]["uuid"];
		WorkspaceIdPath: components["schemas"]["uuid"];
	};
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	getAPIStatus: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["APIStatusResponse"];
				};
			};
		};
	};
	getCSRFToken: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CSRFResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	loginUser: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["LoginRequest"];
			};
		};
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					"Set-Cookie": string;
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AuthResponse"];
				};
			};
			/** @description The server could not understand the request due to invalid syntax. */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	logoutUser: {
		parameters: {
			query?: never;
			header: {
				"X-CSRF-Token": components["parameters"]["CSRFHeader"];
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description There is no content to send for this request, but the headers may be useful. */
			204: {
				headers: {
					"Set-Cookie": string;
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	getCurrentUser: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AuthResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	registerUser: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["RegisterRequest"];
			};
		};
		responses: {
			/** @description The request has succeeded and a new resource has been created as a result. */
			201: {
				headers: {
					"Set-Cookie": string;
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AuthResponse"];
				};
			};
			/** @description The server could not understand the request due to invalid syntax. */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The request conflicts with the current state of the server. */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	getHealth: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HealthResponse"];
				};
			};
			/** @description Service unavailable. */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	listWorkspaces: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["WorkspaceListResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	createWorkspace: {
		parameters: {
			query?: never;
			header: {
				"X-CSRF-Token": components["parameters"]["CSRFHeader"];
			};
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateWorkspaceRequest"];
			};
		};
		responses: {
			/** @description The request has succeeded and a new resource has been created as a result. */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["WorkspaceResponse"];
				};
			};
			/** @description The server could not understand the request due to invalid syntax. */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	getWorkspace: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				workspaceId: components["parameters"]["WorkspaceIdPath"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["WorkspaceResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	deleteWorkspace: {
		parameters: {
			query?: never;
			header: {
				"X-CSRF-Token": components["parameters"]["CSRFHeader"];
			};
			path: {
				workspaceId: components["parameters"]["WorkspaceIdPath"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description There is no content to send for this request, but the headers may be useful. */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	updateWorkspace: {
		parameters: {
			query?: never;
			header: {
				"X-CSRF-Token": components["parameters"]["CSRFHeader"];
			};
			path: {
				workspaceId: components["parameters"]["WorkspaceIdPath"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateWorkspaceRequest"];
			};
		};
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["WorkspaceResponse"];
				};
			};
			/** @description The server could not understand the request due to invalid syntax. */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	listWorkspaceMembers: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				workspaceId: components["parameters"]["WorkspaceIdPath"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["WorkspaceMemberListResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	addWorkspaceMember: {
		parameters: {
			query?: never;
			header: {
				"X-CSRF-Token": components["parameters"]["CSRFHeader"];
			};
			path: {
				workspaceId: components["parameters"]["WorkspaceIdPath"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["AddWorkspaceMemberRequest"];
			};
		};
		responses: {
			/** @description The request has succeeded and a new resource has been created as a result. */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["WorkspaceMemberResponse"];
				};
			};
			/** @description The server could not understand the request due to invalid syntax. */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The request conflicts with the current state of the server. */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	removeWorkspaceMember: {
		parameters: {
			query?: never;
			header: {
				"X-CSRF-Token": components["parameters"]["CSRFHeader"];
			};
			path: {
				workspaceId: components["parameters"]["WorkspaceIdPath"];
				userId: components["parameters"]["UserIdPath"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description There is no content to send for this request, but the headers may be useful. */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The request conflicts with the current state of the server. */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	updateWorkspaceMember: {
		parameters: {
			query?: never;
			header: {
				"X-CSRF-Token": components["parameters"]["CSRFHeader"];
			};
			path: {
				workspaceId: components["parameters"]["WorkspaceIdPath"];
				userId: components["parameters"]["UserIdPath"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateWorkspaceMemberRequest"];
			};
		};
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["WorkspaceMemberResponse"];
				};
			};
			/** @description The server could not understand the request due to invalid syntax. */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The request conflicts with the current state of the server. */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	listTasks: {
		parameters: {
			query?: {
				status?: components["parameters"]["TaskListQuery"];
			};
			header?: never;
			path: {
				workspaceId: components["parameters"]["WorkspaceIdPath"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TaskListResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	createTask: {
		parameters: {
			query?: never;
			header: {
				"X-CSRF-Token": components["parameters"]["CSRFHeader"];
			};
			path: {
				workspaceId: components["parameters"]["WorkspaceIdPath"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateTaskRequest"];
			};
		};
		responses: {
			/** @description The request has succeeded and a new resource has been created as a result. */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TaskResponse"];
				};
			};
			/** @description The server could not understand the request due to invalid syntax. */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	getTask: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				workspaceId: components["parameters"]["WorkspaceIdPath"];
				taskId: components["parameters"]["TaskIdPath"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TaskResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	deleteTask: {
		parameters: {
			query?: never;
			header: {
				"X-CSRF-Token": components["parameters"]["CSRFHeader"];
			};
			path: {
				workspaceId: components["parameters"]["WorkspaceIdPath"];
				taskId: components["parameters"]["TaskIdPath"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description There is no content to send for this request, but the headers may be useful. */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	updateTask: {
		parameters: {
			query?: never;
			header: {
				"X-CSRF-Token": components["parameters"]["CSRFHeader"];
			};
			path: {
				workspaceId: components["parameters"]["WorkspaceIdPath"];
				taskId: components["parameters"]["TaskIdPath"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateTaskRequest"];
			};
		};
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TaskResponse"];
				};
			};
			/** @description The server could not understand the request due to invalid syntax. */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
}
