/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get API status */
		get: operations["getAPIStatus"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/csrf": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get CSRF token */
		get: operations["getCSRFToken"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/gitlab": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Start GitLab OAuth */
		get: operations["startGitLabOAuth"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/gitlab/callback": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Complete GitLab OAuth */
		get: operations["completeGitLabOAuth"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/logout": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Log out user */
		post: operations["logoutUser"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/me": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get current user */
		get: operations["getCurrentUser"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/bootstrap": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get all state required for the first Board render */
		get: operations["getBootstrap"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/cards": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Optimistically create a card */
		post: operations["createCard"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/cards/{issueIid}/assignee": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Optimistically change a card assignee */
		put: operations["updateCardAssignee"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/cards/{issueIid}/details": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Optimistically update card details */
		put: operations["updateCardDetails"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/cards/{issueIid}/due-date": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Optimistically change a card due date */
		put: operations["updateCardDueDate"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/cards/{issueIid}/position": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Optimistically move or close a card */
		put: operations["moveCard"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/cards/{issueIid}/start-date": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Optimistically change a card start date */
		put: operations["updateCardStartDate"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/cards/{issueIid}/team": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Optimistically change a card team */
		put: operations["updateCardTeam"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/directory": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get the normalized SITCON team directory */
		get: operations["getDirectory"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/health/live": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get process liveness */
		get: operations["getLiveness"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/health/ready": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Check database and snapshot readiness */
		get: operations["getReadiness"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/me/preferences": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Confirm the current user's primary team */
		put: operations["updateMyPreferences"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/operations/{operationId}/retry": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Retry a failed durable operation */
		post: operations["retryOperation"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/sync/refresh": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Request a background GitLab refresh */
		post: operations["refreshSnapshots"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/**
		 * @example {
		 *       "name": "SITCON Board API",
		 *       "version": "0.1.0"
		 *     }
		 */
		APIStatusResponse: {
			/** @enum {string} */
			name: "SITCON Board API";
			version: string;
		};
		/**
		 * @example {
		 *       "user": {
		 *         "id": "11111111-1111-1111-1111-111111111111",
		 *         "gitLabUserId": 123456,
		 *         "username": "yorukot",
		 *         "displayName": "Yorukot",
		 *         "avatarUrl": null,
		 *         "profileUrl": "https://gitlab.com/yorukot",
		 *         "accessLevel": 40
		 *       }
		 *     }
		 */
		AuthResponse: {
			user: components["schemas"]["CurrentUser"];
		};
		BoardCard: {
			/** Format: int64 */
			issueIid: number;
			issueId: number | null;
			title: string;
			description: string;
			webUrl: string | null;
			listKey: string;
			/** Format: int32 */
			position: number;
			teamKey: string;
			assigneeGitLabUserIds: number[];
			startDate: string | null;
			dueDate: string | null;
			labels: string[];
			/** @enum {string} */
			syncState: "pending" | "processing" | "synced" | "failed";
			syncError: string | null;
			pendingOperationId: components["schemas"]["uuid"] | null;
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
		};
		BoardList: {
			key: string;
			name: string;
			gitLabLabel: string;
			/** Format: int32 */
			position: number;
			closed: boolean;
			color: string;
		};
		BoardSnapshot: {
			lists: components["schemas"]["BoardList"][];
			cards: components["schemas"]["BoardCard"][];
			/** Format: date-time */
			syncedAt: string;
		};
		BootstrapResponse: {
			me: components["schemas"]["CurrentUser"];
			/** Format: password */
			csrfToken: string;
			teams: components["schemas"]["DirectoryTeam"][];
			members: components["schemas"]["DirectoryMember"][];
			board: components["schemas"]["BoardSnapshot"];
			preferences: components["schemas"]["UserPreferences"];
			sync: components["schemas"]["SyncStatus"];
		};
		/**
		 * @example {
		 *       "token": "csrf-token-readable-by-the-browser-session"
		 *     }
		 */
		CSRFResponse: {
			/** Format: password */
			token: string;
		};
		CardMutationResponse: {
			card: components["schemas"]["BoardCard"];
			operation: components["schemas"]["DurableOperation"];
		};
		CreateCardRequest: {
			operationId: components["schemas"]["uuid"];
			title: string;
			teamKey: string;
			description: string;
			assigneeGitLabUserIds: number[];
			startDate: string | null;
			dueDate: string | null;
		};
		/**
		 * @example {
		 *       "id": "11111111-1111-1111-1111-111111111111",
		 *       "gitLabUserId": 123456,
		 *       "username": "yorukot",
		 *       "displayName": "Yorukot",
		 *       "avatarUrl": "https://gitlab.com/uploads/-/system/user/avatar/123456/avatar.png",
		 *       "profileUrl": "https://gitlab.com/yorukot",
		 *       "accessLevel": 40
		 *     }
		 */
		CurrentUser: {
			id: components["schemas"]["uuid"];
			/** Format: int64 */
			gitLabUserId: number;
			username: string;
			displayName: string;
			/** Format: uri */
			avatarUrl: string | null;
			/** Format: uri */
			profileUrl: string;
			/** Format: int32 */
			accessLevel: number;
		};
		/**
		 * @example {
		 *       "gitLabUserId": 123456,
		 *       "username": "yorukot",
		 *       "displayName": "Yorukot",
		 *       "avatarUrl": null,
		 *       "profileUrl": "https://gitlab.com/yorukot",
		 *       "accessLevel": 40,
		 *       "state": "active",
		 *       "teamKeys": [
		 *         "development"
		 *       ]
		 *     }
		 */
		DirectoryMember: {
			/** Format: int64 */
			gitLabUserId: number;
			username: string;
			displayName: string;
			/** Format: uri */
			avatarUrl: string | null;
			/** Format: uri */
			profileUrl: string;
			/** Format: int32 */
			accessLevel: number;
			/** @enum {string} */
			state: "active" | "blocked" | "deactivated";
			teamKeys: string[];
		};
		DirectoryResponse: {
			directory: components["schemas"]["DirectorySnapshot"];
		};
		DirectorySnapshot: {
			teams: components["schemas"]["DirectoryTeam"][];
			members: components["schemas"]["DirectoryMember"][];
			sourceRevision: string;
			/** Format: date-time */
			syncedAt: string;
		};
		/**
		 * @example {
		 *       "key": "development",
		 *       "name": "開發組",
		 *       "titlePrefix": "[開發組]",
		 *       "gitLabLabel": "組別::開發",
		 *       "active": true,
		 *       "sortOrder": 7,
		 *       "memberGitLabUserIds": [
		 *         123456
		 *       ]
		 *     }
		 */
		DirectoryTeam: {
			key: string;
			name: string;
			titlePrefix: string;
			gitLabLabel: string;
			active: boolean;
			/** Format: int32 */
			sortOrder: number;
			memberGitLabUserIds: number[];
		};
		DurableOperation: {
			id: components["schemas"]["uuid"];
			/** @enum {string} */
			kind: "create_card" | "update_details" | "update_team" | "update_assignee" | "update_start_date" | "update_due_date" | "move_card";
			/** @enum {string} */
			state: "pending" | "processing" | "synced" | "failed";
			/** Format: int32 */
			attempts: number;
			lastError: string | null;
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
		};
		/**
		 * @example {
		 *       "status": "ok"
		 *     }
		 */
		HealthResponse: {
			/** @enum {string} */
			status: "ok";
		};
		MoveCardRequest: {
			operationId: components["schemas"]["uuid"];
			listKey: string;
			/** Format: int32 */
			position: number;
		};
		PreferencesResponse: {
			preferences: components["schemas"]["UserPreferences"];
		};
		/**
		 * @example {
		 *       "type": "https://board.sitcon.org/problems/validation-failed",
		 *       "title": "Validation failed",
		 *       "status": 422,
		 *       "code": "VALIDATION_FAILED",
		 *       "detail": "One or more request fields are invalid.",
		 *       "requestId": "req_01J00000000000000000000000",
		 *       "errors": [
		 *         {
		 *           "code": "REQUIRED",
		 *           "message": "title is required",
		 *           "location": "body.title"
		 *         }
		 *       ]
		 *     }
		 */
		ProblemDetails: {
			/** Format: uri */
			type: string;
			title: string;
			/** Format: int32 */
			status: number;
			/** @enum {string} */
			code:
				| "BAD_REQUEST"
				| "UNAUTHORIZED"
				| "FORBIDDEN"
				| "NOT_FOUND"
				| "CONFLICT"
				| "VALIDATION_FAILED"
				| "INTERNAL_ERROR"
				| "SERVICE_UNAVAILABLE"
				| "METHOD_NOT_ALLOWED"
				| "AUTH_MISSING_SESSION"
				| "AUTH_INVALID_SESSION"
				| "AUTH_INVALID_CSRF"
				| "AUTH_OAUTH_FAILED"
				| "DIRECTORY_NOT_READY"
				| "TEAM_NOT_FOUND"
				| "MEMBER_NOT_ASSIGNABLE"
				| "CARD_NOT_FOUND"
				| "OPERATION_NOT_FOUND"
				| "OPERATION_CONFLICT"
				| "SNAPSHOT_NOT_READY"
				| "GITLAB_UNAVAILABLE";
			detail?: string;
			requestId?: string;
			errors?: components["schemas"]["ProblemError"][];
		};
		/**
		 * @example {
		 *       "code": "REQUIRED",
		 *       "message": "title is required",
		 *       "location": "body.title"
		 *     }
		 */
		ProblemError: {
			/** @enum {string} */
			code:
				| "INVALID_VALUE"
				| "INVALID_JSON"
				| "INVALID_LENGTH"
				| "INVALID_FORMAT"
				| "INVALID_ENUM"
				| "REQUIRED"
				| "VALUE_TOO_SHORT"
				| "VALUE_TOO_LONG"
				| "UNKNOWN_TEAM"
				| "UNKNOWN_MEMBER";
			message: string;
			location?: string;
		};
		RefreshSyncResponse: {
			/** Format: date-time */
			acceptedAt: string;
		};
		RetryOperationResponse: {
			operation: components["schemas"]["DurableOperation"];
		};
		SyncStatus: {
			/** @enum {string} */
			state: "synced" | "syncing" | "offline";
			/** Format: date-time */
			lastSuccessAt: string;
			message: string | null;
		};
		UpdateCardAssigneeRequest: {
			operationId: components["schemas"]["uuid"];
			assigneeGitLabUserIds: number[];
		};
		UpdateCardDetailsRequest: {
			operationId: components["schemas"]["uuid"];
			title: string;
			description: string;
		};
		UpdateCardDueDateRequest: {
			operationId: components["schemas"]["uuid"];
			dueDate: string | null;
		};
		UpdateCardStartDateRequest: {
			operationId: components["schemas"]["uuid"];
			startDate: string | null;
		};
		UpdateCardTeamRequest: {
			operationId: components["schemas"]["uuid"];
			teamKey: string;
		};
		/**
		 * @example {
		 *       "defaultTeamKey": "development"
		 *     }
		 */
		UpdatePreferencesRequest: {
			defaultTeamKey: string;
		};
		/**
		 * @example {
		 *       "defaultTeamKey": "development",
		 *       "confirmedAt": "2026-07-14T08:00:00Z",
		 *       "directoryTeamKeys": [
		 *         "development"
		 *       ]
		 *     }
		 */
		UserPreferences: {
			defaultTeamKey: string | null;
			confirmedAt: string | null;
			directoryTeamKeys: string[];
		};
		/** Format: uuid */
		uuid: string;
	};
	responses: never;
	parameters: {
		CSRFHeader: string;
		"GitLabOAuthCallbackQuery.code": string;
		"GitLabOAuthCallbackQuery.state": string;
		IssueIidPath: number;
		OperationIdPath: components["schemas"]["uuid"];
	};
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	getAPIStatus: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["APIStatusResponse"];
				};
			};
		};
	};
	getCSRFToken: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CSRFResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	startGitLabOAuth: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Redirection */
			302: {
				headers: {
					Location: string;
					"Set-Cookie"?: string;
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	completeGitLabOAuth: {
		parameters: {
			query: {
				code: components["parameters"]["GitLabOAuthCallbackQuery.code"];
				state: components["parameters"]["GitLabOAuthCallbackQuery.state"];
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Redirection */
			302: {
				headers: {
					Location: string;
					"Set-Cookie"?: string;
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description The server could not understand the request due to invalid syntax. */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Service unavailable. */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	logoutUser: {
		parameters: {
			query?: never;
			header: {
				"X-CSRF-Token": components["parameters"]["CSRFHeader"];
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description There is no content to send for this request, but the headers may be useful. */
			204: {
				headers: {
					"Set-Cookie": string;
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	getCurrentUser: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AuthResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	getBootstrap: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["BootstrapResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Service unavailable. */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	createCard: {
		parameters: {
			query?: never;
			header: {
				"X-CSRF-Token": components["parameters"]["CSRFHeader"];
			};
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateCardRequest"];
			};
		};
		responses: {
			/** @description The request has been accepted for processing, but processing has not yet completed. */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CardMutationResponse"];
				};
			};
			/** @description The server could not understand the request due to invalid syntax. */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The request conflicts with the current state of the server. */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Service unavailable. */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	updateCardAssignee: {
		parameters: {
			query?: never;
			header: {
				"X-CSRF-Token": components["parameters"]["CSRFHeader"];
			};
			path: {
				issueIid: components["parameters"]["IssueIidPath"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateCardAssigneeRequest"];
			};
		};
		responses: {
			/** @description The request has been accepted for processing, but processing has not yet completed. */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CardMutationResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The request conflicts with the current state of the server. */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	updateCardDetails: {
		parameters: {
			query?: never;
			header: {
				"X-CSRF-Token": components["parameters"]["CSRFHeader"];
			};
			path: {
				issueIid: components["parameters"]["IssueIidPath"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateCardDetailsRequest"];
			};
		};
		responses: {
			/** @description The request has been accepted for processing, but processing has not yet completed. */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CardMutationResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The request conflicts with the current state of the server. */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	updateCardDueDate: {
		parameters: {
			query?: never;
			header: {
				"X-CSRF-Token": components["parameters"]["CSRFHeader"];
			};
			path: {
				issueIid: components["parameters"]["IssueIidPath"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateCardDueDateRequest"];
			};
		};
		responses: {
			/** @description The request has been accepted for processing, but processing has not yet completed. */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CardMutationResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The request conflicts with the current state of the server. */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	moveCard: {
		parameters: {
			query?: never;
			header: {
				"X-CSRF-Token": components["parameters"]["CSRFHeader"];
			};
			path: {
				issueIid: components["parameters"]["IssueIidPath"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["MoveCardRequest"];
			};
		};
		responses: {
			/** @description The request has been accepted for processing, but processing has not yet completed. */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CardMutationResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The request conflicts with the current state of the server. */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	updateCardStartDate: {
		parameters: {
			query?: never;
			header: {
				"X-CSRF-Token": components["parameters"]["CSRFHeader"];
			};
			path: {
				issueIid: components["parameters"]["IssueIidPath"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateCardStartDateRequest"];
			};
		};
		responses: {
			/** @description The request has been accepted for processing, but processing has not yet completed. */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CardMutationResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The request conflicts with the current state of the server. */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	updateCardTeam: {
		parameters: {
			query?: never;
			header: {
				"X-CSRF-Token": components["parameters"]["CSRFHeader"];
			};
			path: {
				issueIid: components["parameters"]["IssueIidPath"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateCardTeamRequest"];
			};
		};
		responses: {
			/** @description The request has been accepted for processing, but processing has not yet completed. */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CardMutationResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The request conflicts with the current state of the server. */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	getDirectory: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DirectoryResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Service unavailable. */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	getLiveness: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HealthResponse"];
				};
			};
		};
	};
	getReadiness: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HealthResponse"];
				};
			};
			/** @description Service unavailable. */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	updateMyPreferences: {
		parameters: {
			query?: never;
			header: {
				"X-CSRF-Token": components["parameters"]["CSRFHeader"];
			};
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdatePreferencesRequest"];
			};
		};
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PreferencesResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	retryOperation: {
		parameters: {
			query?: never;
			header: {
				"X-CSRF-Token": components["parameters"]["CSRFHeader"];
			};
			path: {
				operationId: components["parameters"]["OperationIdPath"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has been accepted for processing, but processing has not yet completed. */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RetryOperationResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The request conflicts with the current state of the server. */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	refreshSnapshots: {
		parameters: {
			query?: never;
			header: {
				"X-CSRF-Token": components["parameters"]["CSRFHeader"];
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has been accepted for processing, but processing has not yet completed. */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RefreshSyncResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The request conflicts with the current state of the server. */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
}
